initUrl: "jdbc:postgresql://127.0.0.1:5432/"
connUrl: "jdbc:postgresql://127.0.0.1:5432/reproduceDB"
user: "postgres"
password: "postgres"
create: true
load: true
createDatabaseList:
  - "drop database if exists \"reproduceDB\";"
  - "create database \"reproduceDB\";"
createTableList:
  - "create table t(k int primary key, v int);"
loadList:
  - "insert into t values(0, 14458);"
  - "insert into t values(1, 2228);"
  - "insert into t values(2, 481);"
  - "insert into t values(3, 5791);"
  - "insert into t values(4, 18354);"
  - "insert into t values(5, 13176);"
  - "insert into t values(6, 15593);"
  - "insert into t values(7, 3622);"
  - "insert into t values(8, 25032);"
  - "insert into t values(9, 7408);"
  - "insert into t values(10, 30700);"
  - "insert into t values(11, 25491);"
  - "insert into t values(12, 23883);"
  - "insert into t values(13, 27473);"
  - "insert into t values(14, 21566);"
  - "insert into t values(15, 18928);"
  - "insert into t values(16, 20210);"
  - "insert into t values(17, 2708);"
  - "insert into t values(18, 629);"
  - "insert into t values(19, 228);"
  - "insert into t values(20, 13012);"
  - "insert into t values(21, 8560);"
  - "insert into t values(22, 23252);"
  - "insert into t values(23, 5489);"
  - "insert into t values(24, 21213);"
  - "insert into t values(25, 26401);"
  - "insert into t values(26, 22910);"
  - "insert into t values(27, 6711);"
  - "insert into t values(28, 20516);"
  - "insert into t values(29, 10236);"
  - "insert into t values(30, 8069);"
  - "insert into t values(31, 32234);"
  - "insert into t values(32, 7068);"
  - "insert into t values(33, 19887);"
  - "insert into t values(34, 8895);"
  - "insert into t values(35, 12116);"
  - "insert into t values(36, 21698);"
  - "insert into t values(37, 11157);"
  - "insert into t values(38, 27127);"
  - "insert into t values(39, 32704);"
  - "insert into t values(40, 17417);"
  - "insert into t values(41, 23813);"
  - "insert into t values(42, 889);"
  - "insert into t values(43, 14373);"
  - "insert into t values(44, 14325);"
  - "insert into t values(45, 18889);"
  - "insert into t values(46, 27731);"
  - "insert into t values(47, 28580);"
  - "insert into t values(48, 31740);"
  - "insert into t values(49, 28048);"
  - "insert into t values(50, 14150);"
  - "insert into t values(51, 26118);"
  - "insert into t values(52, 21561);"
  - "insert into t values(53, 8060);"
  - "insert into t values(54, 7249);"
  - "insert into t values(55, 12026);"
  - "insert into t values(56, 22238);"
  - "insert into t values(57, 10740);"
  - "insert into t values(58, 32162);"
  - "insert into t values(59, 16185);"
  - "insert into t values(60, 30763);"
  - "insert into t values(61, 25749);"
  - "insert into t values(62, 8728);"
  - "insert into t values(63, 31106);"
operationList:
  - trxId: "0"
    sql: "SELECT k FROM t WHERE k=0;"
  - trxId: "1"
    sql: "UPDATE t SET v=1804289383 where k=0;"
  - trxId: "1"
    sql: "SELECT v FROM t WHERE k=1;"
  - trxId: "1"
    sql: "COMMIT;"
  - trxId: "2"
    sql: "SELECT v FROM t WHERE k=2;"
  - trxId: "2"
    sql: "UPDATE t SET v=846930886 where k=1;"
  - trxId: "2"
    sql: "COMMIT;"
  - trxId: "0"
    sql: "UPDATE t SET v=1681692777 where k=2;"
  - trxId: "0"
    sql: "COMMIT;"
